--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TDB-Network/TDBJail
build-by-default: true
branches:
  - master
projects:
  TDBJail:
    path: ""
    libs:
      - format: virion
        vendor: poggit-project
        src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3

...
